use_frameworks!
platform :ios, '11.0'

target 'fuikit_Example' do
  pod 'fuikit', :path => '../'
  pod 'LithoOperators', git: 'https://github.com/LithoByte/LithoOperators'
  target 'fuikit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
